version: '3.8'

services:
  user-service:
    image: wisepen/user-service:latest
    container_name: wisepen-user-service
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: wisepen-user-service/wisepen-user-biz/target/*.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod # 必须使用prod, 否则Nacos拉取的是dev的配置（默认），下同
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-user-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/user:/logs
    networks:
      - cloud-net

  system-service:
    image: wisepen/system-service:latest
    container_name: wisepen-system-service
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: wisepen-system-service/wisepen-system-biz/target/*.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-system-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      - cloud-net

  resource-service:
    image: wisepen/resource-service:latest
    container_name: wisepen-resource-service
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: wisepen-resource-service/wisepen-resource-biz/target/*.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-resource-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      - cloud-net

  document-service:
    image: wisepen/document-service:latest
    container_name: wisepen-document-service
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: wisepen-document-service/wisepen-document-biz/target/*.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-document-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      - cloud-net

  file-storage-service:
    image: wisepen/file-storage-service:latest
    container_name: wisepen-file-storage-service
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: wisepen-file-storage-service/wisepen-file-storage-biz/target/*.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-file-storage-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      - cloud-net

  fudan-extension-service:
    image: wisepen/fudan-extension-service:latest
    container_name: wisepen-fudan-extension-service
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: wisepen-fudan-extension-service/wisepen-fudan-extension-biz/target/*.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - OTEL_SERVICE_NAME=wisepen-fudan-extension-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CLOUD_INETUTILS_PREFERRED_NETWORKS=
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
    volumes:
      - ../logs/system:/logs
    networks:
      - cloud-net

networks:
  cloud-net:
    external: true
    name: cloud-infra_cloud-net